Repository redpwn/rctf, pull requests merged in 2020-04, with the labels that each got.

#156 Remove session fixiation vulnerability
  client/src/components/tokenPreview.js
  client/src/routes/profile.js
  client/src/routes/verify.js
Labels: bug

#164 fix(client): whitelist class prefix selectors in PurgeCSS
  preact.config.js
Labels: bug

#167 fix(client): remove manually-loaded polyfills
  client/src/index.js
  package.json
  yarn.lock
Labels: bug

#173 Clean up loader test editing in client build
  preact.config.js
Labels: refactoring

#186 Rewrite Graph component with hooks
  client/src/components/graph.js
Labels: refactoring

#190 Add admin challenge data API
  server/api/admin/challs/get.js
  server/api/admin/challs/index.js
  server/api/admin/challs/list.js
  server/api/admin/challs/put.js
  server/api/index.js
  server/challenges/Provider.ts
  server/challenges/index.ts
  server/providers/challenges/rdeploy-blob/index.ts
  server/responses/index.js
  server/util/perms.js
Labels: enhancement

#196 Add markdown parsing of challenge descriptions
  client/src/routes/challenges.js
  package.json
  yarn.lock
Labels: enhancement

#198 fix(build): overwrite files when copying static files
  package.json
Labels: bug

#199 fix: make migrate down work on migrations
  migrations/1581725957097_del-password.js
  migrations/1582424634372_string-uuids.js
  migrations/1585799727940_add-ctftime-id.js
Labels: bug

#202 feat(client): restyle or divider in login / register
  client/src/components/ctftime-button.js
  client/src/components/or.js
  client/src/routes/login.js
  client/src/routes/registration.js
Labels: enhancement
