Repository redpwn/rctf, pull requests merged in 2020-03, with the labels that each got.

#72 Improve install scripts
  Dockerfile
  README.md
  install/config.sh
  install/install.sh
Labels: bug, enhancement

#88 Improve install script
  install/install.sh
Labels: refactoring

#94 Add support for configuration through CLI
  .dockerignore
  .gitignore
  README.md
  docs/rctf-cli.png
  install/install.sh
  install/rctf.py
  package-lock.json
Labels: enhancement

#102 Allow querystring parameters as an object in request
  client/src/api/scoreboard.js
  client/src/api/util.js
Labels: refactoring

#83 Create pluggable provider system for challenges
  config/server.js
  server/challenges/Provider.ts
  server/challenges/index.js
  server/challenges/index.ts
  server/challenges/types.ts
  server/providers/challenges/rdeploy-blob/index.ts
  test/_util.js
  test/integration/submit.js
  test/integration/submitTiming.js
  test/unit/challenges/index.js
  test/unit/challenges/providers/rdeploy-blob/index.js
Labels: refactoring

#104 Add scoreboard pagination
  client/src/components/pagination.jsx
  client/src/pages/profile.js
  client/src/pages/scoreboard.js
  server/api/users/util.js
Labels: enhancement

#112 feat(api): add server support for leaderboard graphs
  client/src/api/scoreboard.js
  config/server.js
  server/api/index.js
  server/api/leaderboard/graph.js
  server/api/leaderboard/now.js
  server/cache/leaderboard.js
  server/database/solves.js
  server/leaderboard/calculate.js
  server/leaderboard/index.js
  server/leaderboard/samples.js
  test/integration/leaderboard.js
  yarn.lock
Labels: enhancement

#123 Add modal for confirming account deletion
  client/src/components/modal.js
  client/src/pages/profile.js
Labels: enhancement

#124 Restyle account deletion dialog
  client/src/pages/profile.js
Labels: bug

#127 Make account deletion dialog update when you type
  client/src/pages/profile.js
Labels: bug

#125 Reimplement toasts
  client/src/api/profile.js
  client/src/components/toast.js
  client/src/index.js
  client/src/pages/challenges.js
  client/src/pages/profile.js
  client/src/util/index.js
  client/src/util/toasts/Toast.js
  client/src/util/toasts/context.js
  client/src/util/toasts/index.js
  client/src/util/toasts/useToast.js
  client/src/util/toasts/withToastProvider.js
  yarn.lock
Labels: refactoring

#133 Update preact-cli, clean up client build
  .gitignore
  .travis.yml
  client/build.sh
  client/index.html
  client/src/assets/logo-256.png
  client/src/components/modal.js
  client/src/icons/address-book.svg
  client/src/icons/envelope-open.svg
  client/src/icons/id-card.svg
  client/src/icons/rank.svg
  client/src/icons/trophy.svg
  client/src/icons/user-circle.svg
  client/src/index.js
  client/src/pages/index.js
  client/src/routes/challenges.js
  client/src/routes/error.js
  client/src/routes/home.js
  client/src/routes/login.js
  client/src/routes/logout.js
  client/src/routes/profile.js
  client/src/routes/registration.js
  client/src/routes/scoreboard.js
  client/src/routes/sponsors.js
  client/src/routes/verify.js
  client/src/static/favicon.ico
  client/src/static/security.txt
  package.json
  preact.config.js
  yarn.lock
Labels: refactoring

#139 Use hooks in Profile page
  client/src/routes/profile.js
Labels: refactoring

#137 Use SVG sprites for icons
  client/lib/svg-icon-component-generator.js
  client/src/components/icon.js
  package.json
  preact.config.js
  yarn.lock
Labels: refactoring

#146 UI improvements
  client/src/routes/challenges.js
  client/src/routes/home.js
  client/src/routes/login.js
  client/src/routes/profile.js
  client/src/routes/registration.js
  client/src/routes/scoreboard.js
  client/src/routes/sponsors.js
Labels: enhancement

#148 Split linting out to a separate job
  .travis.yml
Labels: enhancement
