Repository redpwn/rctf, pull requests merged in 2020-08, with the labels that each got.

#443 refactor(server): type server util files
  package.json
  server/util/index.ts
  server/util/perms.js
  server/util/perms.ts
  server/util/validate.ts
  yarn.lock
Labels: refactoring

#459 refactor(server): enable strict mode on TS code
  server/challenges/index.ts
  server/database/challenges.ts
  server/database/index.ts
  server/database/members.ts
  server/database/migrate.ts
  server/database/solves.ts
  server/database/users.ts
  server/providers/challenges/database/index.ts
  server/providers/emails/mailgun/index.ts
  server/providers/emails/ses/index.ts
  server/providers/emails/smtp/index.ts
  server/providers/uploads/gcs/index.ts
  server/providers/uploads/local/index.ts
  tsconfig.json
Labels: refactoring

#460 refactor(server): type server auth files
  package.json
  server/auth/index.ts
  server/auth/register.js
  server/auth/register.ts
  server/auth/token.js
  server/auth/token.ts
  yarn.lock
Labels: refactoring

#461 refactor(server): type email provider loader
  server/email/index.js
  server/email/index.ts
  server/email/provider.ts
Labels: refactoring

#462 misc type fixes
  server/auth/token.ts
  server/database/users.ts
  server/util/restrict.ts
  test/unit/restrict.js
Labels: bug

#303 refactor(server): add and enforce stricter ts config
  package.json
  server/.eslintrc.js
  server/challenges/Provider.ts
  server/challenges/index.ts
  server/config/server.ts
  server/database/challenges.ts
  server/database/members.ts
  server/database/solves.ts
  server/database/users.ts
  server/database/util.ts
  server/providers/emails/smtp/index.ts
  server/providers/uploads/gcs/index.ts
  server/providers/uploads/local/index.ts
  server/uploads/index.ts
  server/uploads/types.ts
  server/util/index.ts
  yarn.lock
Labels: refactoring

#466 feat(server): add config option for proxy trust
  docs/content/configuration.md
  server/app.js
  server/config/server.ts
  server/util/index.ts
Labels: enhancement
