Repository redpwn/rctf, pull requests merged in 2020-06, with the labels that each got.

#320 feat(client): support ctftime modifcations for existing users
  client/src/api/auth.js
  client/src/components/ctftime-button.js
  client/src/components/profile/ctftime-card.js
  client/src/components/profile/members-card.js
  client/src/routes/login.js
  client/src/routes/profile.js
  client/src/routes/register.js
  client/src/static/favicon.ico
  client/src/static/security.txt
  server/api/integrations-ctftime/callback.js
Labels: enhancement

#330 refactor(server): parallelize user data fetching
  server/api/users/util.js
Labels: enhancement

#319 feat(server): add upload exists api
  server/api/admin/index.js
  server/api/admin/upload/exists.js
  server/api/admin/upload/index.js
  server/api/admin/upload/post.js
  server/providers/uploads/dummy/index.ts
  server/providers/uploads/gcs/index.ts
  server/providers/uploads/local/index.ts
  server/responses/index.js
  server/uploads/types.ts
Labels: enhancement

#329 feat(server): more detailed logging of API events
  server/api/index.js
  server/api/submitflag.js
  server/app.js
Labels: enhancement

#318 fix(server): fix raw index html being accessible
  server/util/index.js
Labels: bug

#327 refactor(server): move api numeric type validation to schema
  server/api/auth/register.js
  server/api/leaderboard/graph.js
  server/api/leaderboard/now.js
  server/api/users/update.js
Labels: refactoring

#350 feat(server): log user-agent
  server/app.js
Labels: enhancement

#377 feat(client): save scoreboard settings on client
  client/src/routes/challs.js
  client/src/routes/scoreboard.js
Labels: enhancement
