Repository redpwn/rctf, pull requests merged in 2020-07, with the labels that each got.

#412 Update fastify (and plugins) to v3
  package.json
  server/api/leaderboard/graph.js
  server/api/leaderboard/now.js
  server/app.js
  server/providers/uploads/local/index.ts
  server/uploads/index.ts
  yarn.lock
Labels: dependencies, javascript

#426 fix(client): fix fetch loop when no challenges exist
  client/src/routes/challs.js
Labels: bug

#428 feature: email division assignment
  client/src/api/auth.js
  client/src/api/profile.js
  client/src/routes/profile.js
  client/src/routes/register.js
  client/src/routes/scoreboard.js
  config/yml.example/server.yml
  config/yml.example/shared.yml
  docs/content/configuration.md
  server/api/auth/register.js
  server/api/auth/verify.js
  server/api/leaderboard/graph.js
  server/api/leaderboard/now.js
  server/api/users/me-auth/email/put.js
  server/api/users/me.js
  server/api/users/update.js
  server/api/users/util.js
  server/cache/leaderboard.js
  server/database/auth.js
  server/errors/index.js
  server/leaderboard/calculate.js
  server/responses/index.js
  server/util/index.js
  server/util/restrict.ts
  test/_util.js
  test/unit/restrict.js
Labels: enhancement
